/* eslint-disable */

const tailwindTypography = require('@tailwindcss/typography');
const scrollbarHide = require('tailwind-scrollbar-hide');

const globalConfig = {
  mod: 'jit',
  content: [],
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    extend: {
      keyframes: {
        loading: {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(150%)' },
        },
        'loading-v2': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(200%)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
      },
      animation: {
        loading: 'loading 1s ease-in-out infinite alternate',
        'loading-v2': 'loading-v2 1s ease-in-out infinite',
      },
      colors: {
        'BLACK-1': 'rgb(var(--y-black-1) / <alpha-value>)',
        'BLACK-2': 'rgb(var(--y-black-2) / <alpha-value>)',
        'BLACK-3': 'rgb(var(--y-black-3) / <alpha-value>)',
        BLACKOVERLAY: 'rgb(var(--y-overlay) / 0.5)',
        BLUE: 'rgb(var(--y-blue) / <alpha-value>)',
        'BLUE-2': 'rgb(var(--y-blue-2) / <alpha-value>)',
        'BLUE-3': 'rgb(var(--y-blue) / 0.12)',
        BUD: 'rgb(var(--y-bud) / <alpha-value>)',
        'HOVER-BLUE': 'rgb(var(--y-hover-blue) / <alpha-value>)',
        'HOVER-BLUE-0.2': 'rgb(var(--y-hover-blue) / 0.2)',
        BORDER: 'rgb(var(--y-border) / <alpha-value>)',
        BROWN: 'rgb(var(--y-brown) / <alpha-value>)',
        DARKBROWN: 'rgb(var(--y-darkbrown) / <alpha-value>)',
        FUCHSIA: 'rgb(var(--y-fuchsia) / <alpha-value>)',
        GREEN: 'rgb(var(--y-green) / <alpha-value>)',
        'GREEN-2': 'rgb(var(--y-green-2) / <alpha-value>)',
        'GREY-1': 'rgb(var(--y-grey-1) / <alpha-value>)',
        'GREY-2': 'rgb(var(--y-grey-2) / <alpha-value>)',
        'GREY-3': 'rgb(var(--y-grey-3) / <alpha-value>)',
        'GREY-4': 'rgb(var(--y-grey-4) / <alpha-value>)',
        'GREY-5': 'rgb(var(--y-grey-5) / <alpha-value>)',
        'GREY-6': 'rgb(var(--y-grey-6) / <alpha-value>)',
        'GREY-7': 'rgb(var(--y-grey-7) / <alpha-value>)',
        'GREY-8': 'rgb(var(--y-grey-8) / 0.2)',
        'GREY-9': 'rgb(var(--y-grey-9) / <alpha-value>)',
        'GREY-10': 'rgb(var(--y-grey-7) / 0.5)',
        INDIGO: 'rgb(var(--y-indigo) / <alpha-value>)',
        'LIGHTBLUE-1': 'rgb(var(--y-lightblue-1) / <alpha-value>)',
        'LIGHTBLUE-2': 'rgb(var(--y-lightblue-2) / <alpha-value>)',
        'LIGHTBLUE-3': 'rgb(var(--y-lightblue-3) / <alpha-value>)',
        'LIGHTBLUE-4': 'rgb(var(--y-lightblue-4) / <alpha-value>)',
        'LIGHTBLUE-5': 'rgb(var(--y-lightblue-5) / <alpha-value>)',
        'LIGHTBLUE-6': 'rgb(var(--y-lightblue-6) / <alpha-value>)',
        'LIGHTBLUE-7': 'rgb(var(--y-lightblue-7) / <alpha-value>)',
        'LIGHTBLUE-8': 'rgb(var(--y-lightblue-8) / <alpha-value>)',
        'LIGHTBLUE-9': 'rgb(var(--y-lightblue-9) / <alpha-value>)',
        OCEAN: 'rgb(var(--y-ocean) / <alpha-value>)',
        ORANGE: 'rgb(var(--y-orange) / <alpha-value>)',
        PINK: 'rgb(var(--y-pink) / <alpha-value>)',
        RED: 'rgb(var(--y-red) / <alpha-value>)',
        'RED-2': 'rgb(var(--y-red-2) / <alpha-value>)',
        'RED-3': 'rgb(var(--y-red-3) / <alpha-value>)',
        'RED-4': 'ffc3c81a',
        TEAL: 'rgb(var(--y-teal) / <alpha-value>)',
        KEPPEL: 'rgb(var(--y-keppel) / <alpha-value>)',
        EMERALD: 'rgb(var(--y-emerald) / <alpha-value>)',
        VIOLET: 'rgb(var(--y-violet) / <alpha-value>)',
        WHITE: 'rgb(var(--y-white) / <alpha-value>)',
        YELLOW: 'rgb(var(--y-yellow) / <alpha-value>)',
        'BLACK-16': 'rgb(var(--y-black-1) / 0.2)',
        'BLUE-20': 'rgb(var(--y-blue) / 0.2)',
        'RED-20': 'rgb(var(--y-red) / 0.2)',
        'GREEN-20': 'rgb(var(--y-green) / 0.2)',
        'YELLOW-20': 'rgb(var(--y-yellow) / 0.2)',
        'ORANGE-20': 'rgb(var(--y-orange) / 0.2)',
        'TEAL-20': 'rgb(var(--y-teal) / 0.2)',
        'INDIGO-20': 'rgb(var(--y-indigo) / 0.2)',
        'DARKBROWN-20': 'rgb(var(--y-darkbrown) / 0.2)',
        'BROWN-20': 'rgb(var(--y-brown) / 0.2)',
        'OCEAN-20': 'rgb(var(--y-ocean) / 0.2)',
        'VIOLET-20': 'rgb(var(--y-violet) / 0.2)',
        'FUCHSIA-20': 'rgb(var(--y-fuchsia) / 0.2)',
        'PINK-20': 'rgb(var(--y-pink) / 0.2)',
      },
      backgroundColor: {
        white: 'rgb(var(--y-white) / <alpha-value>)',
        'BLACK-1': 'rgb(var(--y-ink-1) / <alpha-value>)',
        'BLACK-2': 'rgb(var(--y-ink-2) / <alpha-value>)',
        'BLACK-3': 'rgb(var(--y-ink-3) / <alpha-value>)',
      },
      borderColor: {
        DEFAULT: 'rgb(var(--y-border) / <alpha-value>)',
        white: 'rgb(var(--y-white) / <alpha-value>)',
      },
      textColor: {
        white: 'rgb(var(--y-on-color) / <alpha-value>)',
      },
      divideColor: {
        white: 'rgb(var(--y-white) / <alpha-value>)',
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': 'rgb(var(--y-black-1))',
            '--tw-prose-headings': 'rgb(var(--y-black-3))',
            '--tw-prose-lead': 'rgb(var(--y-black-2))',
            '--tw-prose-links': 'rgb(var(--y-blue))',
            '--tw-prose-bold': 'rgb(var(--y-black-3))',
            '--tw-prose-counters': 'rgb(var(--y-grey-6))',
            '--tw-prose-bullets': 'rgb(var(--y-grey-1))',
            '--tw-prose-hr': 'rgb(var(--y-border))',
            '--tw-prose-quotes': 'rgb(var(--y-black-2))',
            '--tw-prose-quote-borders': 'rgb(var(--y-border))',
            '--tw-prose-captions': 'rgb(var(--y-grey-6))',
            '--tw-prose-code': 'rgb(var(--y-black-1))',
            '--tw-prose-pre-code': 'rgb(var(--y-grey-3))',
            '--tw-prose-pre-bg': 'rgb(var(--y-ink-1))',
            '--tw-prose-th-borders': 'rgb(var(--y-border))',
            '--tw-prose-td-borders': 'rgb(var(--y-border))',
          },
        },
      },
      spacing: {
        63: '268px',
        10.5: '42px',
        17: '70px',
        55: '216px',
        22: '88px',
      },
      width: {
        '1/2-gap-1': 'calc((100% - 0.25rem) / 2)',
        '1/2-gap-2': 'calc((100% - 0.5rem) / 2)',
        '1/3-gap-2': 'calc((100% - 1rem) / 3)',
        '2/3-gap-2': 'calc(((100% - 1rem) / 3) * 2)',
        '1/4-gap-2': 'calc((100% - 1.5rem) / 4)',
        '1/5-gap-2': 'calc((100.00% - 2rem) / 5)',
        '1/2-gap-3': 'calc((100% - 0.75rem) / 2)',
        '1/3-gap-3': 'calc((100% - 1.5rem) / 3)',
        '2/3-gap-3': 'calc(((100% - 1.5rem) / 3) * 2)',
        '1/4-gap-3': 'calc((100% - 2.25rem) / 4)',
        '1/5-gap-3': 'calc((100% - 3rem) / 5)',
        '1/2-gap-4': 'calc((100.00% - 1rem) / 2)',
        '1/3-gap-4': 'calc((100% - 2rem) / 3)',
        '1/4-gap-4': 'calc((100.00% - 3rem) / 4)',
        '1/5-gap-4': 'calc((100.00% - 4rem) / 5)',
        '3/5-gap-4': 'calc(((100% - 1rem) / 5) * 3)',
        '2/5-gap-4': 'calc(((100% - 1rem) / 5) * 2)',
        '1/2-gap-5': 'calc((100% - 1.25rem)  / 2)',
        '1/2-gap-6': 'calc((100% - 1.5rem)  / 2)',
        '1/3-gap-6': 'calc((100% - 3rem)  / 3)',
        '1/4-gap-6': 'calc((100.00% - 4.5rem) / 4)',
        '1/5-gap-6': 'calc((100.00% - 6rem) / 5)',
        '1/3-gap-8': 'calc((100% - 2rem) / 3)',
        '2/3-gap-8': 'calc(((100% - 2rem) / 3) * 2)',
        '1/2-gap-9': 'calc((100% - 2.25rem) / 2)',
        '1/3-gap-9': 'calc((100% - 4.5rem) / 3)',
        '1/4-gap-9': 'calc((100% - 6.75rem) / 4)',
        '1/5-gap-9': 'calc((100% - 9rem) / 5)',
        46: '11.25rem',
        60: '3.75rem',
      },
      fontSize: {
        '3xs': '0.5rem',
        '2xs': '0.625rem',
        '6.5xl': '4rem',
        '3.25xl': ['2rem', '2.5rem'],
      },
      boxShadow: {
        1: '0 16px 40px 0 rgba(13, 30, 91, 0.08)',
        2: '0 6px 12px 0 rgba(13, 30, 91, 0.08)',
        3: '0 20px 80px 0 rgba(13, 30, 91, 0.08)',
        4: '0 1px 2px 0 #00000033',
        5: '0 3px 8px rgba(0, 0, 0, 0.12)',
        6: '0 16px 48px rgba(0, 0, 0, 0.22)',
      },
      borderWidth: {
        3: '3px',
        6: '6px',
      },
      zIndex: {
        1: '1',
        2: '2',
        3: '3',
        4: '4',
        5: '5',
        6: '6',
        7: '7',
        8: '8',
        9: '9',
        11: '11',
        12: '12',
        13: '13',
        14: '14',
        15: '15',
        16: '16',
        17: '17',
        18: '18',
        19: '19',
        21: '21',
        22: '22',
        23: '23',
        24: '24',
        25: '25',
        26: '26',
        27: '27',
        28: '28',
        29: '29',
        31: '31',
        32: '32',
        33: '33',
        34: '34',
        35: '35',
        36: '36',
        37: '37',
        38: '38',
        39: '39',
        41: '41',
        42: '42',
        43: '43',
        44: '44',
        45: '45',
        46: '46',
        47: '47',
        48: '48',
        49: '49',
        50: '50',
        51: '51',
        1000: '1000',
        1001: '1001',
        1002: '1002',
      },
      minWidth: {
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        32: '8rem',
        42: '10rem',
        44: '11rem',
        54: '13.5rem',
        60: '15rem',
        62: '15.5rem',
        64: '16rem',
        80: '20rem',
        96: '24rem',
        112: '28rem',
        128: '32rem',
        140: '36rem',
        156: '40rem',
      },
      maxWidth: {
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        32: '8rem',
        42: '10rem',
        44: '11rem',
        54: '13.5rem',
        60: '15rem',
        62: '15.5rem',
        64: '16rem',
        80: '20rem',
        96: '24rem',
        112: '28rem',
        128: '32rem',
        140: '36rem',
        156: '40rem',
      },
      minHeight: {
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        32: '8rem',
        42: '10rem',
        44: '11rem',
        54: '13.5rem',
        60: '15rem',
        62: '15.5rem',
        64: '16rem',
        80: '20rem',
        96: '24rem',
        112: '28rem',
        128: '32rem',
        140: '36rem',
        156: '40rem',
      },
      maxHeight: {
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        8: '2rem',
        9: '2.25rem',
        32: '8rem',
        42: '10rem',
        44: '11rem',
        54: '13.5rem',
        60: '15rem',
        62: '15.5rem',
        64: '16rem',
        80: '20rem',
        96: '24rem',
        112: '28rem',
        128: '32rem',
        140: '36rem',
        156: '40rem',
      },
      backgroundSize: {
        16: '1rem',
        20: '1.25rem',
        24: '1.5rem',
        32: '2rem',
        56: '3.5rem',
        60: '3.75rem',
        84: '5.25rem',
        96: '6rem',
        120: '7.5rem',
        156: '9.75rem',
      },
    },
    screens: {
      '5xs': '360px',
      // => @media (min-width: 360px) { ... }
      '4xs': '475px',
      // => @media (min-width: 475px) { ... }
      '3xs': '576px',
      // => @media (min-width: 576px) { ... }
      '2xs': '640px',
      // => @media (min-width: 640px) { ... }
      xs: '768px',
      // => @media (min-width: 768px) { ... }
      sm: '960px',
      // => @media (min-width: 960px) { ... }
      md: '1024px',
      // => @media (min-width: 1024px) { ... }
      lg: '1280px',
      // => @media (min-width: 1280px) { ... }
      xl: '1440px',
      // => @media (min-width: 1440px) { ... }
      '2xl': '1600px',
      // => @media (min-width: 1600px) { ... }
      '3xl': '1920px',
      // => @media (min-width: 1920px) { ... }
      '4xl': '2560px',
      // => @media (min-width: 2560px) { ... }
    },
    blur: {
      xs: '2px',
    },
  },
  variants: {
    extend: {
      backgroundColor: ['checked', 'active', 'before'],
      borderColor: ['checked', 'active', 'before'],
      ringColor: ['hover', 'active', 'before'],
      margin: ['first', 'last'],
    },
  },
  plugins: [],
};

let projectConfig = {};

try {
  projectConfig = require('../../../yartu.config.js');
} catch {
  console.info('You can create yartu.config.js to override theme configs.');
}

const mergedConfig = { ...globalConfig, ...projectConfig };

mergedConfig.content.push(
  './node_modules/@yartu/ui-kit/components/**/*.{vue,js,ts,jsx,tsx}',
);

mergedConfig.plugins = mergedConfig.plugins.concat([
  tailwindTypography,
  scrollbarHide,
]);

module.exports = mergedConfig;
